AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  EnabledByDefault: true
  Exclude:
    - bin/**/*
    - vendor/**/*
  ExtraDetails: true
  NewCops: enable
  TargetRubyVersion: 3.2
  UseCache: true

inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  sakuro-rubocop-config:
    - config/cops/bundler.yml
    - config/cops/gemspec.yml
    - config/cops/layout.yml
    - config/cops/lint.yml
    - config/cops/metrics.yml
    - config/cops/naming.yml
    - config/cops/performance.yml
    - config/cops/rake.yml
    - config/cops/rspec.yml
    - config/cops/security.yml
    - config/cops/style.yml

inherit_from: .rubocop_todo.yml

# Project-specific settings can be added here
Naming/VariableNumber:
  AllowedPatterns:
    - '^(january|february|march|april|may|june|july|august|september|october|november|december)_\d{4}$'  # month_YYYY
    - '^(leap|non_leap)_\d{4}$'  # leap_YYYY, non_leap_YYYY

Style/EmptyElse:
  Enabled: false

Style/FetchEnvVar:
  # Allow ENV["key"] for these variables as nil return values are intentionally handled
  AllowedVars:
    - LC_ALL        # Used for locale detection, nil is acceptable
    - LANG          # Used for locale detection, nil is acceptable
    - XDG_CONFIG_HOME  # Used in tests for environment backup/restore, nil is acceptable

Style/SymbolProc:
  # Allow OptionParser#accept method which requires specific block format incompatible with symbol-to-proc
  AllowedMethods:
    - accept

Layout/LineLength:
  # Exclude test files with long test data strings
  Exclude:
    - 'spec/fasti/style_parser_spec.rb'

Metrics/ParameterLists:
  # Don't count keyword arguments as they are named and improve readability
  CountKeywordArgs: false

Metrics/BlockLength:
  # Exclude CLI file which contains long OptionParser DSL block
  Exclude:
    - 'lib/fasti/cli.rb'
