---
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  EnabledByDefault: true
  Exclude:
  - bin/**/*
  - vendor/**/*
  - benchmark/**/*
  ExtraDetails: true
  TargetRubyVersion: 3.4
  UseCache: true
inherit_mode:
  merge:
  - Exclude
plugins:
  - rubocop-rspec
  - rubocop-rake
require: []
inherit_from:
  - .rubocop/bundler.yml
  - .rubocop/gemspec.yml
  - .rubocop/layout.yml
  - .rubocop/lint.yml
  - .rubocop/metrics.yml
  - .rubocop/migration.yml
  - .rubocop/naming.yml
  - .rubocop/rake.yml
  - .rubocop/rspec.yml
  - .rubocop/security.yml
  - .rubocop/style.yml
  - .rubocop_todo.yml

Naming/VariableNumber:
  AllowedPatterns:
    - '^(january|february|march|april|may|june|july|august|september|october|november|december)_\d{4}$'  # month_YYYY
    - '^(leap|non_leap)_\d{4}$'  # leap_YYYY, non_leap_YYYY

Style/EmptyElse:
  Enabled: false

Style/FetchEnvVar:
  # Allow ENV["key"] for these variables as nil return values are intentionally handled
  AllowedVars:
    - LC_ALL        # Used for locale detection, nil is acceptable
    - LANG          # Used for locale detection, nil is acceptable
    - XDG_CONFIG_HOME  # Used in tests for environment backup/restore, nil is acceptable

Style/SymbolProc:
  # Allow OptionParser#accept method which requires specific block format incompatible with symbol-to-proc
  AllowedMethods:
    - accept

Layout/LineLength:
  # Exclude test files with long test data strings
  Exclude:
    - 'spec/fasti/style_parser_spec.rb'
